### ISSUE TITLE
What about namespaces?

### ISSUE THREAD

**Issue by mr-koww** [rf-/keynote#17]
Hello! How I can use this wonderful gem with scope (namespace)? For example:
```
class Clients::MenuPresenter < Keynote::Presenter
...
end
```
and
```
class Workers::MenuPresenter < Keynote::Presenter
...
end
```
Thank you!

**Comment by rf-** [comment]
Hi! I believe you can use a slash in the presenter name, since we're using Rails' constantize method: `present(:"workers/menu", foo)`. I should probably document that and add a test case though.

**Comment by mr-koww** [comment]
Thanks, it work's fine!
